version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
  mysql:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: 195495b
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: danny
      MYSQL_PASSWORD: 195495
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8980:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql


volumes:
  mysql_data:
