version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./www:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 195495b
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: danny
      MYSQL_PASSWORD: 195495
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
